apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: service-a  # Must match the Deployment's labels
  ports:
    - protocol: TCP
      port: 5000       # Internal cluster-wide service port
      targetPort: 5000 # Must match `containerPort` in Deployment
      nodePort: 30001  # External port (must be 30000-32767)
  type: NodePort
